fos_rest:
    routing_loader: false
    body_listener: true
    view:
        mime_types:
            json: ['application/json']
        view_response_listener: 'force'
        formats:
            xml: false
            json: true
            html: false
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
