parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $importDir: '%kernel.project_dir%/var/import'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
